[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
viaIR = true
fs_permissions = [{ access = "read-write", path = "./" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
